trigger:
- main  # Trigger the pipeline on commits to the main branch

pool:
  name: 'aks-pool'  # Use your AKS agent pool here

steps:
- checkout: self  # Checkout the repository where hello.txt is located

- script: |
    cat hello.txt  # Read and display the contents of hello.txt
  displayName: 'Display Contents of hello.txt'

